name: Deploy VitalAxis

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t tayraps/vitalaxis:latest .
      - run: docker push tayraps/vitalaxis:latest
